services:
  nats:
    image: nats:latest
    container_name: aerovibe-nats
    ports:
      - "127.0.0.1:4222:4222"
      - "127.0.0.1:8222:8222"
    command: "-js"
    environment:
      - "JS_ENABLE=true"
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: aerovibe-redis
    ports:
      - "127.0.0.1:6379:6379"
    restart: unless-stopped
